server:
  port: 18080

spring:
  profiles:
    active: dev
  application:
    name: cloud-springboot-jsp
  mvc:
    view:
      prefix: /view/
      suffix: .jsp

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeEnumsPackage: com.hello.jsp.springboot.enums
  global-config:
    db-config:
      id-type: auto
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: full
    default-executor-type: reuse
    default-statement-timeout: 600
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl