server:
  port: 8080

spring:
  application:
    name: cloud-springboot-jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 153156@Tao
  mvc:
    view:
      prefix: /view/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.helloworld.springboot.model

person: {name: haohao,age: 31,addr: beijing}

sitetArray:
  -http://www.taobao.com
  -http://www.tmall.com
